name: Bluebird 
version: 1.0
description: A Twitter plugin for Statamic v2.x
url: https://github.com/mc72
developer: Mike Ciccone (original addon by Nick Snyder)
developer_url: https://github.com/mc72
